config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get :dashboard, to: 'dashboard#index'

  # Resources
  resources :items, only: :create do
    get :download
  end

  # Authentication
  get :signout, to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
end

app/models/item.rb
class Item < ActiveRecord::Base
  CONTENT_TYPES = ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  belongs_to :user
  has_attached_file :document

  validates :user, presence: true
  validates_attachment :document, content_type: { content_type: CONTENT_TYPES }

  def to_jq_upload
    {
      name: document_file_name,
      size: document_file_size,
      url: document.url(:original),
      created_at: created_at.to_s(:short)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items, dependent: :destroy
  has_attached_file :image

  validates_attachment :image, content_type: {
                                 content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
                               }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :signup_required

  helper_method :signed_in?, :current_user

  def signed_in?
    current_user.present?
  end

  def current_user
    return @current_user if defined? @current_user
    get_current_user
  end

  private

  def signup_required
    signed_in? || redirect_to(root_path)
  end

  def get_current_user
    if session[:user_id] && user = User.find_by(id: session[:user_id])
      @current_user ||= user
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @item = Item.new
    @items = current_user.items.order created_at: :desc
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    item = Item.new item_params
    item.user = current_user

    respond_to do |format|
      if item.save
        format.html { redirect_to root_path }
        format.json { render json: { files: [item.to_jq_upload]}, status: :created, location: root_path }
      else
        format.html { redirect_to root_path }
        format.json { render json: item.errors, status: :unprocessable_entity }
      end
    end
  end

  def download
    item = Item.find(params[:item_id])
    send_file item.document.path
  end

  private

  def item_params
    params.require(:item).permit :document
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :signup_required
  before_action :goto_dashboard

  private

  def goto_dashboard
    return unless signed_in?
    redirect_to dashboard_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :signup_required, only: [:create, :failure]

  def create
    sign_user_in
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out!'
  end

  def failure
    redirect_to root_path, notice: 'Please try again later.'
  end

  private

  def auth_hash
    request.env['omniauth.auth'].with_indifferent_access
  end

  def user_from_auth
    UserFromAuth.new(auth_hash).find_or_build
  end

  def sign_user_in
    SignUserIn.new(session, user_from_auth).commence!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @item = Item.new
    @items = Item.order created_at: :desc
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.haml
.row
  .col-md-6
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Type
          %th Size
          %th Created
          %th
      %tbody
        - @items.each do |item|
          %tr
            %td= item.document_file_name
            %td= item.document_content_type
            %td= number_to_human_size item.document_file_size
            %td= item.created_at.to_s(:short)
            %td
              = link_to item_download_path(item), class: 'btn btn-default btn-xs btn-success' do
                = fa_icon 'arrow-circle-down'
                download
  .col-md-6
    .jumbotron.text-center.upload-area
      = fa_icon 'cloud-upload', class: 'fa-5x'
      %p Drag & Drop Files Here
      %span.btn.btn-primary.fileinput-button
        %span Select files here
        = file_field_tag :document, name: 'documents[]', accept: Item::CONTENT_TYPES, multiple: true

app/views/landing/index.haml
.jumbotron
  %h1 Keep your files with Keeper!
  %p
    Fast and easy way to store your files in the cloud. More features like file sharing, soon...
  %p
    Keep calm! Winter is coming...

app/views/layouts/_navbar.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{ data: { target: '.navbar-inverse-collapse', toggle: 'collapse' }, type: 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: '#' } Keeper
    .navbar-collapse.collapse.navbar-inverse-collapse
      - if signed_in?
        %form.navbar-form.navbar-left
          %input.form-control.col-lg-12{ placeholder: 'Search', type: 'text' }
      %p.navbar-text.navbar-right
        - if signed_in?
          = link_to 'Sign out', signout_path, class: 'btn btn-xs btn-default'
        - else
          = link_to 'Sign in', '/auth/google', class: 'btn btn-xs btn-default'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Keeper
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container
      = yield